[graph]
# Targets I care for
targets = ['x86_64-unknown-linux-gnu', 'x86_64-pc-windows-msvc']

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "EUPL-1.2", "Unicode-3.0", "Zlib"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "deny"
skip = [
    { crate = "windows_x86_64_msvc@0.52.6", reason = "The windows crates are notoriously duplicate" },
    { crate = "windows_x86_64_gnu@0.52.6", reason = "The windows crates are notoriously duplicate" },
    { crate = "windows-targets@0.52.6", reason = "The windows crates are notoriously duplicate" },
    { crate = "windows-sys@0.59.0", reason = "The windows crates are notoriously duplicate" },
]
