
# cargo-vet audits file

[[audits.cc]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.2.12 -> 1.2.15"

[[audits.clap]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "4.5.29 -> 4.5.30"

[[audits.clap_builder]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "4.5.29 -> 4.5.30"

[[audits.log]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.4.25 -> 0.4.26"

[[audits.pkg-config]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.3.29 -> 0.3.30"
notes = "This change just adds documentation."

[[audits.serde]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.217 -> 1.0.218"

[[audits.serde_derive]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.217 -> 1.0.218"

[[audits.smallvec]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.6.1 -> 1.8.0"

[[audits.tinyvec_macros]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.1"
notes = "Explicitly forbids unsafe code now; remaining changes is just new license files"

[[audits.unicode-ident]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.16 -> 1.0.17"

[[trusted.cc]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2024-02-20"
end = "2025-10-27"
notes = "Trusted by Mozilla and Bytecode Alliance"

[[trusted.clap_derive]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2025-10-27"
notes = "Trusted by Mozilla and Bytecode Alliance"

[[trusted.git2]]
criteria = "safe-to-run"
user-id = 4333
start = "2020-08-19"
end = "2025-10-27"
notes = "Trusted by Mozilla and Bytecode Alliance"

[[trusted.git2]]
criteria = "safe-to-run"
user-id = 55123 # rust-lang-owner
start = "2023-08-28"
end = "2026-01-29"

[[trusted.jobserver]]
criteria = "safe-to-run"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-15"
end = "2025-10-27"
notes = "Trusted by Mozilla and Bytecode Alliance"

[[trusted.libc]]
criteria = "safe-to-run"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-02-22"

[[trusted.libgit2-sys]]
criteria = "safe-to-run"
user-id = 4333
start = "2020-08-19"
end = "2025-10-27"
notes = "Trusted by Mozilla and Bytecode Alliance"

[[trusted.libgit2-sys]]
criteria = "safe-to-run"
user-id = 55123 # rust-lang-owner
start = "2023-08-28"
end = "2026-01-29"

[[trusted.libz-sys]]
criteria = "safe-to-run"
user-id = 980 # Sebastian Thiel (Byron)
start = "2023-07-23"
end = "2026-02-22"

[[trusted.libz-sys]]
criteria = "safe-to-run"
user-id = 4333
start = "2020-08-14"
end = "2025-10-27"
notes = "Trusted by Mozilla and Bytecode Alliance"

[[trusted.syn]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-02-22"
